name: Run Node.js Scripts and Update Changelog
description: This workflow runs Node.js scripts to convert images, generate thumbnails, and update the changelog when changes are pushed to the main branch.

on:
  push:
    branches:
      - main # Or the branch you want to trigger on

permissions:
  contents: write # Grant write permission to the GITHUB_TOKEN

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files at repository root (for debugging)
        run: ls -al /home/runner/work/MasterHome/MasterHome/ # List files in the checked-out repo

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a suitable Node.js version

      - name: Install dependencies
        run: npm install # Install project dependencies, including 'sharp'
        working-directory: . # Explicitly run npm install at the repository root

      - name: Run WebP Converter script
        run: node ./assets/Media/webp-converter.js # Ensure this path is correct relative to the repo root
        working-directory: . # Run script from repository root

      - name: Run Thumbnail Generator script
        run: node ./assets/Media/generate-thumb.js # Ensure this path is correct relative to the repo root
        working-directory: . # Run script from repository root

      - name: Run Assets JSON Generator script
        run: node ./assets/generate-assets-json.js # Ensure this path is correct relative to the repo root
        working-directory: . # Run script from repository root

      - name: Run changelog generator script
        run: node ./changelog-gen.js # Ensure this path is correct relative to the repo root
        working-directory: . # Run script from repository root
        env:
          TOKEN: ${{ secrets.TOKEN }} # Set the TOKEN environment variable from GitHub secrets

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./changelog.json # Ensure this path is correct relative to the repo root
          git commit -m "Update changelog.json" || echo "No changes to commit"
          git push
